# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BragCli < Formula
  desc "Track engineering accomplishments for performance reviews"
  homepage "https://github.com/eduardohitek/brag-cli"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eduardohitek/brag-cli/releases/download/v0.3.0/brag_0.3.0_darwin_amd64.tar.gz"
      sha256 "dfbcb38907990a789167ed8a2e09c9ae3655ff050376805e3c72f10c77e0a0ae"

      define_method(:install) do
        bin.install "brag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eduardohitek/brag-cli/releases/download/v0.3.0/brag_0.3.0_darwin_arm64.tar.gz"
      sha256 "5c67fbae5879d3758dfc64e664ef5ab476bb470c9e0caa796f2616d796536b9a"

      define_method(:install) do
        bin.install "brag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eduardohitek/brag-cli/releases/download/v0.3.0/brag_0.3.0_linux_amd64.tar.gz"
      sha256 "7b85c89262bc213981bdfc65b1bd4e2600a5869e134902eda878984b868c6349"
      define_method(:install) do
        bin.install "brag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eduardohitek/brag-cli/releases/download/v0.3.0/brag_0.3.0_linux_arm64.tar.gz"
      sha256 "376138b6155ea812628731edc2ea88300b8d4ffdb19eb922a114fc9d0c8e9a9d"
      define_method(:install) do
        bin.install "brag"
      end
    end
  end

  test do
    system "#{bin}/brag --version"
  end
end
