# This file was generated by GoReleaser. DO NOT EDIT.
cask "brag" do
  name "brag"
  desc "Automated bragdoc collector"
  homepage "https://github.com/eduardohitek/brag-cli"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brag"

  on_macos do
    on_intel do
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_darwin_amd64.tar.gz"
      sha256 "4163ed0e6ee54b2c82d68fe1a600ebcd9ef875d00e607dad9c873b2498e44aa1"
    end
    on_arm do
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_darwin_arm64.tar.gz"
      sha256 "107c715f1e997f7e44e9e18b9dc024fddb7180de17138bec9659f941a12cce4c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_linux_amd64.tar.gz"
      sha256 "e8b3aacc46aa6dd6497b0dec1152890635ec1e38c15c36e9a2d4a95f6bc71345"
    end
    on_arm do
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_linux_arm64.tar.gz"
      sha256 "e0c25a44b51bd73a32b1c373ac527e538c42e083ba99ba60d9704055b0a74ba7"
    end
  end

  # No zap stanza required
end
