# This file was generated by GoReleaser. DO NOT EDIT.
cask "brag" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "brag"], chdir: "."
    end
  end

  version "0.10.1"

  on_macos do
    on_arm do
      sha256 "f829aa3db708c1e0b42e7b243ddcae40c965b67ce75184b1dc33b1a18c3b3466"
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aa1e35c093bdc95342c8e6b07585db4ed6bb7d7e6e760bcc3ba4d898238f8bae"
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "25f2cc888402bff1b4f2b56ffce11230213a01db3e73f2cc8a0aa558f8a0cce6"
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "13ed905c0d3c8e7d1df01cfee9f3fd809b1429627114e8cb4214c56269864d5c"
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_linux_amd64.tar.gz"
    end
  end

  name "brag"
  desc "Automated bragdoc collector"
  homepage "https://github.com/eduardohitek/brag-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brag"

  # No zap stanza required
end
