# This file was generated by GoReleaser. DO NOT EDIT.
cask "brag" do
  name "brag"
  desc "Automated bragdoc collector"
  homepage "https://github.com/eduardohitek/brag-cli"
  version "0.7.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brag"

  on_macos do
    on_intel do
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_darwin_amd64.tar.gz"
      sha256 "22ab9c2ec505814f3dd43330bd5c8eb168478e0644229ea911e32d81c1d82adf"
    end
    on_arm do
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_darwin_arm64.tar.gz"
      sha256 "17c30f218ebaf26fc4de6c7c267761e9bfc61b4743b4b101a6f066cf37ca99b7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_linux_amd64.tar.gz"
      sha256 "03c023252995401b63b76b75d7d70f2fe7739369890750acfe47ef054a565594"
    end
    on_arm do
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_linux_arm64.tar.gz"
      sha256 "d8a4b7b4dea5e4d26ec8c37d8391f494900afb19b6064880dd44033948e6cc5c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/brag"]
    end
  end

  # No zap stanza required
end
