# This file was generated by GoReleaser. DO NOT EDIT.
cask "brag-cli" do
  name "brag-cli"
  desc "Automated bragdoc collector"
  homepage "https://github.com/eduardohitek/brag-cli"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brag-cli"

  on_macos do
    on_intel do
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_darwin_amd64.tar.gz"
      sha256 "ab641437e7e425f4ed31160c0c1f2d822d38ed71d6398e9b0305c95b23058030"
    end
    on_arm do
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_darwin_arm64.tar.gz"
      sha256 "9ac4273cad43ac4279958f9cc44a7cadcc9928acd93ffb4411403eeb976c7d6e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_linux_amd64.tar.gz"
      sha256 "1e5d351d43cbb402826f889193864a19ae3f762a3ae223a67b51a1762114b6b6"
    end
    on_arm do
      url "https://github.com/eduardohitek/brag-cli/releases/download/v#{version}/brag_#{version}_linux_arm64.tar.gz"
      sha256 "6acd7992592bdea4e795295e43dcb1f2e833ca441ff9776bd84a498e8e4d48f3"
    end
  end

  # No zap stanza required
end
